const actions = {
  GET_FRIENDS: 'GET_FRIENDS',
  REMOVE_FRIEND: 'REMOVE_FRIEND',

  GET_MOVIES: 'GET_MOVIES',
  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE',

  DEVIN_FUN: 'DEVIN_FUN',
};

export default actions;
